import  {setConnected, 
        setFacebookId,
        setUserInformation,
        setAllQuestions,
        setCurrentQuestion,
        setEditorOptions,
        setSourceCode,
        setAllCoderResults,
        setRetrievedResult,
        setDifficultyFilteredQuestions, 
        setWaitingCodeSubmission ,
        setCurrentResult,
        setMessengerId,
        setIndividualRanking,
        setAllRanking,
        setMessengerExtensions,
        setProgrammingQuestionExplanation,
        setCodingGroundResults,
        setTestResults,
        setAllCourses,
        setCourseData,
        setCourseSegmentData} from  './actionCreators'

export default {
    setConnected,
    setFacebookId, 
    setUserInformation,
    setAllQuestions,
    setCurrentQuestion,
    setEditorOptions,
    setSourceCode,
    setAllCoderResults,
    setRetrievedResult,
    setDifficultyFilteredQuestions,
    setWaitingCodeSubmission,
    setCurrentResult,
    setMessengerId,
    setIndividualRanking,
    setAllRanking,
    setMessengerExtensions,
    setProgrammingQuestionExplanation,
    setCodingGroundResults,
    setTestResults,
    setAllCourses,
    setCourseData,
    setCourseSegmentData
}

